In [1]:
# 화면 가로 확장 코드 (기본 width 50%)
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:70% !important; }</style>"))

In [ ]:
import os
try:
    os.mkdir('./Combined_Data')
except FileExistsError:
    print('해당 폴더가 이미 존재합니다.\n폴더를 확인해주세요.')

In [ ]:
import pandas as pd
import csv

month = {1:31, 2:28, 3:31, 4:30, 5:31, 6:30, 7:31, 8:31, 9:30, 10:31, 11:30, 12:31}

for y in range(2013, 2017):
    
    for m in range(1,13):
        csv_electric = pd.read_csv("./Electric_Data/Electirc_Data_CSV_FInal/"+str(y)+"/"+str(y)+'_'+str(m)+'_'+"House1_Ch1_Electric_Data_Final.csv", encoding='cp949')
        csv_weather = pd.read_csv("./Weather_Data/Weather_Data_24H_CSV/"+str(y)+"/"+str(y)+'_'+str(m)+'_'+"London_Temperature_24H.csv", encoding='cp949')
        s = 0
        for d in range(month[m]):
            d=d+1 
            for n in range(s, s+24):
                with open("./Electirc_Data_CSV_Final/"+str(y)+'_'+str(m)+'_'+"House1_Ch1_Electric_Data_Final.csv", 'a', newline='') as file:
                                writer = csv.writer(file)
                                writer.writerow(new_list)
                                
            s=s+24
#csv_origin.to_csv("./Electirc_Data_CSV_Final/"+str(y)+'_'+str(m)+'_'+"House1_Ch1_Electric_Data_Final.csv", encoding='euc-kr')            
print('\n------------------------------< Job Done!! >------------------------------\n')

In [11]:
import pandas as pd

y = 2013
m=1
csv_electric = pd.read_csv("./Electric_Data/Electirc_Data_CSV_FInal/"+str(y)+"/"+str(y)+'_'+str(m)+'_'+"House1_Ch1_Electric_Data_Final.csv", encoding='cp949')
csv_weather = pd.read_csv("./Weather_Data/Weather_Data_24H_CSV/"+str(y)+"/"+str(y)+'_'+str(m)+'_'+"London_Temperature_24H.csv", encoding='utf-8')
csv_electric.head(48)

    Unnamed: 0           DateTime Day Holiday  Seq  Watt
0            0   2013년 1월 1일 - 0시   화       O    0  2495
1            1   2013년 1월 1일 - 1시   화       O    1  2482
2            2   2013년 1월 1일 - 2시   화       O    2  2441
3            3   2013년 1월 1일 - 3시   화       O    3   265
4            4   2013년 1월 1일 - 4시   화       O    4   260
5            5   2013년 1월 1일 - 5시   화       O    5   260
6            6   2013년 1월 1일 - 6시   화       O    6   326
7            7   2013년 1월 1일 - 7시   화       O    7   372
8            8   2013년 1월 1일 - 8시   화       O    8  4444
9            9   2013년 1월 1일 - 9시   화       O    9  2691
10          10  2013년 1월 1일 - 10시   화       O   10  2558
11          11  2013년 1월 1일 - 11시   화       O   11   779
12          12  2013년 1월 1일 - 12시   화       O   12  2961
13          13  2013년 1월 1일 - 13시   화       O   13   529
14          14  2013년 1월 1일 - 14시   화       O   14  3032
15          15  2013년 1월 1일 - 15시   화       O   15  2869
16          16  2013년 1월 1일 - 16시   화       O   16   354
17          17  2013년 1월 1일 - 17시   화       O   17  2297
18          18  2013년 1월 1일 - 18시   화       O   18  2184
19          19  2013년 1월 1일 - 19시   화       O   19  2981
20          20  2013년 1월 1일 - 20시   화       O   20   729
21          21  2013년 1월 1일 - 21시   화       O   21  2122
22          22  2013년 1월 1일 - 22시   화       O   22   543
23          23  2013년 1월 1일 - 23시   화       O   23   572
24          24   2013년 1월 2일 - 0시   수       X    0  1913
25          25   2013년 1월 2일 - 1시   수       X    1   240
26          26   2013년 1월 2일 - 2시   수       X    2   231
27          27   2013년 1월 2일 - 3시   수       X    3   307
28          28   2013년 1월 2일 - 4시   수       X    4   328
29          29   2013년 1월 2일 - 5시   수       X    5   238
30          30   2013년 1월 2일 - 6시   수       X    6  1080
31          31   2013년 1월 2일 - 7시   수       X    7   345
32          32   2013년 1월 2일 - 8시   수       X    8  2728
33          33   2013년 1월 2일 - 9시   수       X    9   551
34          34  2013년 1월 2일 - 10시   수       X   10   569
35          35  2013년 1월 2일 - 11시   수       X   11  3304
36          36  2013년 1월 2일 - 12시   수       X   12  2945
37          37  2013년 1월 2일 - 13시   수       X   13  2911
38          38  2013년 1월 2일 - 14시   수       X   14  3145
39          39  2013년 1월 2일 - 15시   수       X   15  1109
40          40  2013년 1월 2일 - 16시   수       X   16  3083
41          41  2013년 1월 2일 - 17시   수       X   17   726
42          42  2013년 1월 2일 - 18시   수       X   18  2214
43          43  2013년 1월 2일 - 19시   수       X   19   778
44          44  2013년 1월 2일 - 20시   수       X   20   951
45          45  2013년 1월 2일 - 21시   수       X   21   917
46          46  2013년 1월 2일 - 22시   수       X   22   710
47          47  2013년 1월 2일 - 23시   수       X   23   326

In [12]:
csv_weather.head(48)

    Unnamed: 0  Year  Month  Day  Seq  Temp °C
0            0  2013      1    1    0  10.0  ℃
1            1  2013      1    1    1   9.0  ℃
2            2  2013      1    1    2   8.5  ℃
3            3  2013      1    1    3   8.0  ℃
4            4  2013      1    1    4   8.0  ℃
5            5  2013      1    1    5   7.0  ℃
6            6  2013      1    1    6   6.0  ℃
7            7  2013      1    1    7   5.5  ℃
8            8  2013      1    1    8   5.0  ℃
9            9  2013      1    1    9   5.0  ℃
10          10  2013      1    1   10   5.5  ℃
11          11  2013      1    1   11   6.5  ℃
12          12  2013      1    1   12   7.0  ℃
13          13  2013      1    1   13   7.5  ℃
14          14  2013      1    1   14   7.5  ℃
15          15  2013      1    1   15   7.0  ℃
16          16  2013      1    1   16   6.5  ℃
17          17  2013      1    1   17   6.0  ℃
18          18  2013      1    1   18   6.0  ℃
19          19  2013      1    1   19   6.0  ℃
20          20  2013      1    1   20   6.0  ℃
21          21  2013      1    1   21   6.0  ℃
22          22  2013      1    1   22   5.5  ℃
23          23  2013      1    1   23   5.0  ℃
24          24  2013      1    2    0  10.0  ℃
25          25  2013      1    2    1   9.0  ℃
26          26  2013      1    2    2   8.5  ℃
27          27  2013      1    2    3   8.0  ℃
28          28  2013      1    2    4   8.0  ℃
29          29  2013      1    2    5   7.0  ℃
30          30  2013      1    2    6   6.0  ℃
31          31  2013      1    2    7   5.5  ℃
32          32  2013      1    2    8   5.0  ℃
33          33  2013      1    2    9   5.0  ℃
34          34  2013      1    2   10   5.5  ℃
35          35  2013      1    2   11   6.5  ℃
36          36  2013      1    2   12   7.0  ℃
37          37  2013      1    2   13   7.5  ℃
38          38  2013      1    2   14   7.5  ℃
39          39  2013      1    2   15   7.0  ℃
40          40  2013      1    2   16   6.5  ℃
41          41  2013      1    2   17   6.0  ℃
42          42  2013      1    2   18   6.0  ℃
43          43  2013      1    2   19   6.0  ℃
44          44  2013      1    2   20   6.0  ℃
45          45  2013      1    2   21   6.0  ℃
46          46  2013      1    2   22   5.5  ℃
47          47  2013      1    2   23   5.0  ℃